services:
  app:
    image: 'todo-frontend-dev'
    container_name: 'todo-frontend-dev'
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './:/usr/src/app'
