services:
  app:
    image: 'todo-frontend-dev'
    container_name: 'todo-frontend-dev'
    build:
      context: .
      dockerfile: dev.Dockerfile

    # commented out ports because we are using nginx reverse proxy

    # ports:
    #   - '3000:3000'
    volumes:
      - './:/usr/src/app'
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=0
