services:
  app:
    extends:
      file: ./todo-frontend/docker-compose.yml
      service: app
    depends_on:
      api:
        condition: service_started
  api:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: app
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
  mongo:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: mongo
  redis:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: redis
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    depends_on:
      app:
        condition: service_started
