services:
  dev.app:
    container_name: dev.app
    extends:
      file: ./todo-frontend/docker-compose.dev.yml
      service: dev.app
    depends_on:
      dev.api:
        condition: service_started
  dev.api:
    container_name: dev.api
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: dev.app
    depends_on:
      dev.mongo:
        condition: service_started
      dev.redis:
        condition: service_started
  dev.mongo:
    container_name: dev.mongo
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: dev.mongo
  dev.redis:
    container_name: dev.redis
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: dev.redis
  dev.nginx:
    image: nginx:1.25.0-bullseye
    container_name: dev.reverse-proxy
    ports:
      - '8080:80'
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      dev.app:
        condition: service_started
  dev.debug-helper:
    image: busybox
    container_name: dev.debug-helper
