version: '3.8'

services:
  app:
    image: todo-backend
    build:
      context: .
      dockerfile: Dockerfile

    # commented out ports because we are using nginx reverse proxy
    # ports:
    #   - 4000:4000
    container_name: todo-backend
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data_prod:/data/db
  redis:
    image: redis
    container_name: redis
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes:
      - ./redis_data_prod:/data
  debug-helper:
    image: busybox
    container_name: debug-helper
